# Setup

### Import Dependencies

In [35]:
import pandas as pd
import geopandas as gpd
import geopy
import numpy as np
import re
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import matplotlib.pyplot as plt
import folium
from folium.plugins import FastMarkerCluster

# Import Data

### Import the full finishers list

In [36]:
# bring in the csv
df = pd.read_csv("../00_data/raw_data/M2019_finishers.csv")
df.head()

,name,geo_subregion,country,gender,age,bib,team,official_time,pace_per_mile,place_overall,...,20m,21m,35k,22m,23m,24m,40k,25m,26m,mar
0,Michel Butter,Castricum,NLD,M,33,7,New Balance,2:25:06,05:33,37,...,1:43:56,1:50:22,1:55:04,1:56:42,2:03:26,2:10:32,2:16:06,2:17:07,2:23:41,2:25:06
1,Geoffrey Kamworor,Kapchorwa District,KEN,M,26,3,NIKE,2:08:13,04:54,1,...,1:38:59,1:44:07,1:47:34,1:48:44,1:53:20,1:57:59,2:01:48,2:02:30,2:07:11,2:08:13
2,Jack Rayner,Melbourne,AUS,M,23,9,NIKE,2:16:58,05:14,22,...,1:40:59,1:46:40,1:50:55,1:52:22,1:58:10,2:04:07,2:08:58,2:09:51,2:15:39,2:16:58
3,Stephen Sambu,"Tucson, AZ",USA,M,31,10,NIKE,2:11:11,05:01,7,...,1:39:12,1:44:15,1:47:58,1:49:13,1:54:16,1:59:39,2:03:59,2:04:46,2:09:58,2:11:11
4,Jared Ward,"Mapleton, UT",USA,M,31,6,Saucony,2:10:45,05:00,6,...,1:39:13,1:44:15,1:47:57,1:49:12,1:54:16,1:59:35,2:03:47,2:04:34,2:09:37,2:10:45

In [37]:
df.info(verbose = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53639 entries, 0 to 53638
Data columns (total 54 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   name                   53639 non-null  object
 1   geo_subregion          53622 non-null  object
 2   country                53639 non-null  object
 3   gender                 53639 non-null  object
 4   age                    53639 non-null  int64
 5   bib                    53639 non-null  int64
 6   team                   9282 non-null   object
 7   official_time          53639 non-null  object
 8   pace_per_mile          53639 non-null  object
 9   place_overall          53639 non-null  object
 10  place_gender           53639 non-null  object
 11  age_group              53639 non-null  object
 12  place_age-group        53639 non-null  object
 13  country_group          53637 non-null  object
 14  place_country          53639 non-null  object
 15  place_age‐graded       53639 non-null  object
 16  time_age‐graded        53639 non-null  object
 17  percentage_age‐graded  53639 non-null  object
 18  gun_time               53639 non-null  object
 19  gun_place              53639 non-null  int64
 20  3m                     53557 non-null  object
 21  5k                     53594 non-null  object
 22  4m                     53557 non-null  object
 23  5m                     53585 non-null  object
 24  6m                     53372 non-null  object
 25  10k                    53558 non-null  object
 26  7m                     53567 non-null  object
 27  8m                     53598 non-null  object
 28  9m                     53542 non-null  object
 29  15k                    53550 non-null  object
 30  10m                    53569 non-null  object
 31  11m                    53547 non-null  object
 32  12m                    53576 non-null  object
 33  20k                    53447 non-null  object
 34  13m                    53519 non-null  object
 35  half                   53467 non-null  object
 36  14m                    53532 non-null  object
 37  15m                    53412 non-null  object
 38  25k                    53517 non-null  object
 39  16m                    53502 non-null  object
 40  17m                    53548 non-null  object
 41  18m                    53455 non-null  object
 42  30k                    53338 non-null  object
 43  19m                    53176 non-null  object
 44  20m                    53150 non-null  object
 45  21m                    53303 non-null  object
 46  35k                    53379 non-null  object
 47  22m                    53365 non-null  object
 48  23m                    53135 non-null  object
 49  24m                    53357 non-null  object
 50  40k                    53202 non-null  object
 51  25m                    53431 non-null  object
 52  26m                    53344 non-null  object
 53  mar                    53639 non-null  object
dtypes: int64(3), object(51)
memory usage: 22.1+ MB

### Set up country coding assistant

In [38]:
class GroupMap:
    def __init__(self):
        self.data = {}
        
    # Based on discussion here: https://stackoverflow.com/questions/55892600/python-triplet-dictionary
    # Takes in a dictionary and creates an identical dictionary under each value in the original.
    # This provides a means to look up keys from values.
    # For example, {'a':'apple', 'b':'butter', 'c':'cocoa'} is stored as
    # {'apple':{'a':'apple', 'b':'butter', 'c':'cocoa'},
    # 'butter':{'a':'apple', 'b':'butter', 'c':'cocoa'},
    # 'cocoa':{'a':'apple', 'b':'butter', 'c':'cocoa'}}
    # so, self['butter'] returns {'a':'apple', 'b':'butter', 'c':'cocoa'}, 
    # and self['butter']['a'] returns 'apple'.
    # Be warned, newer entries overwrite older ones.

    def add(self, group):
        for thing in group.keys():
            self.data[group[thing]] = group

    def __getitem__(self, item):
        return self.data[item]

In [39]:
# Read in the conversion table from Wikipedia.
temp_df = pd.read_html('https://en.wikipedia.org/wiki/Comparison_of_alphabetic_country_codes')[0]    


# Tidy up the columm headings.
temp_df = temp_df[['Country', 'IOC', 'ISO']]
temp_df = temp_df.rename(columns={'IOC': 'IOC_code', 'ISO': 'ISO_code'})

# Drop the footnote citations from the table text.
citation_pattern = re.compile('\[[1-9][0-9]?\]')

temp_df['Country'] = temp_df['Country'].str.replace(citation_pattern,'')

# Drop the parenthetical notes from the table text. (Note the leading space.)
parenthetical_pattern = re.compile(' \(.+\)')

temp_df['Country'] = temp_df['Country'].str.replace(parenthetical_pattern,'')

# Reorder the comma separated entries.
temp_df['Country'] = temp_df['Country'].str.split(', ').apply(lambda x: ' '.join(x[::-1]))

In [40]:
country_code_trictionary = GroupMap()

thang = temp_df.to_dict('records')

for record in thang:
    country_code_trictionary.add(record)

In [41]:
def country_coder(country_query, desired_code):
    try:
        output = country_code_trictionary[country_query][desired_code]
        return output
    except:
        return None

# Data Prep and Cleaning

In [42]:
# First we need to correct some known errors in the data.

# Countries

# Some addresses for China (CHN) are mis-coded as 'CHI'.
df['country'] = df['country'].str.replace('CHI','CHN')

# Some addresses for Romania (ROU) are mis-coded as 'ROM'.
df['country'] = df['country'].str.replace('ROM','ROU')

# Some addresses for the Democratic Republic of the Congo (COD) are mis-coded as 'Dem'
df['country'] = df['country'].str.replace('Dem','COD')

# One address for the USA (USA) is mis-coded as 'Sai'
df['country'] = df['country'].str.replace('Sai','USA')

# Geo_subregions

# The periods in 'L.I.C.' generate errors.
df['geo_subregion'] = df['geo_subregion'].str.replace('L.I.C.','Long Island City')

In [43]:
# How many countries are represented?
len(df['country'].unique())

137

In [44]:
# Now convert the country abbreviations to the expanded country names.
# The geocoder is a lot more successful with expanded names.

df['long_country'] = df['country'].apply(lambda country: country_coder(country, 'Country'))

In [45]:
# How many records were not expandable?

df.long_country.isnull().sum()

0

# Geocoding

### Pull in known addresses

In [46]:
address_list_df = pd.read_csv("address_cache.csv")
address_list_df.head()

,address,full_address,location
0,Castricum Netherlands,"Castricum, Noord-Holland, Nederland","(52.558830549999996, 4.639675526200153)"
1,Kapchorwa District Kenya,"District Farm Institute, Sironko Kapchorwa Roa...","(1.2992853, 34.3193213)"
2,Melbourne Australia,"Melbourne, City of Melbourne, Victoria, 3000, ...","(-37.8142176, 144.9631608)"
3,"Tucson, AZ United States","Tucson, Pima County, Arizona, United States","(32.2228765, -110.9748477)"
4,"Mapleton, UT United States","Mapleton, Utah County, Utah, 84664, United States","(40.1302338, -111.5785281)"

### Merge known addresses to the finisher data

In [47]:
# construct an 'address' for geocoding purposes
df['address'] = df['geo_subregion'] + " " + df['long_country']

# Merge with the cached address list.
df = df.merge(address_list_df, how='left', on='address')

In [48]:
df.head()

,name,geo_subregion,country,gender,age,bib,team,official_time,pace_per_mile,place_overall,...,23m,24m,40k,25m,26m,mar,long_country,address,full_address,location
0,Michel Butter,Castricum,NLD,M,33,7,New Balance,2:25:06,05:33,37,...,2:03:26,2:10:32,2:16:06,2:17:07,2:23:41,2:25:06,Netherlands,Castricum Netherlands,"Castricum, Noord-Holland, Nederland","(52.558830549999996, 4.639675526200153)"
1,Geoffrey Kamworor,Kapchorwa District,KEN,M,26,3,NIKE,2:08:13,04:54,1,...,1:53:20,1:57:59,2:01:48,2:02:30,2:07:11,2:08:13,Kenya,Kapchorwa District Kenya,"District Farm Institute, Sironko Kapchorwa Roa...","(1.2992853, 34.3193213)"
2,Jack Rayner,Melbourne,AUS,M,23,9,NIKE,2:16:58,05:14,22,...,1:58:10,2:04:07,2:08:58,2:09:51,2:15:39,2:16:58,Australia,Melbourne Australia,"Melbourne, City of Melbourne, Victoria, 3000, ...","(-37.8142176, 144.9631608)"
3,Stephen Sambu,"Tucson, AZ",USA,M,31,10,NIKE,2:11:11,05:01,7,...,1:54:16,1:59:39,2:03:59,2:04:46,2:09:58,2:11:11,United States,"Tucson, AZ United States","Tucson, Pima County, Arizona, United States","(32.2228765, -110.9748477)"
4,Jared Ward,"Mapleton, UT",USA,M,31,6,Saucony,2:10:45,05:00,6,...,1:54:16,1:59:35,2:03:47,2:04:34,2:09:37,2:10:45,United States,"Mapleton, UT United States","Mapleton, Utah County, Utah, 84664, United States","(40.1302338, -111.5785281)"

In [52]:
df['location'][0].split(', ')[1]

'4.639675526200153)'

In [14]:
# How many records still need geocoding?

df.location.isnull().sum()

694

### Create an address list for geocoding

In [15]:
# build a list of unique addresses so that we can spend less time making geocode requests.
address_list = df.loc[df['location'].isnull(), 'address'].unique()
len(address_list)

535

In [16]:
address_list

array(['Kapkitony Kenya', "New Taipei City People's Republic of China",
       'O Fallon, MO United States', 'Chesitek Kenya', nan,
       "Hsinchu City People's Republic of China", 'Fpo, AP United States',
       'København Sv Denmark', "Miaoli County People's Republic of China",
       'Loenen Gld Netherlands', 'Seoul, Mapo-gu United States',
       'Nakorn Ratchasima Thailand', 'North Plainfiel, NJ United States',
       'Steeplechase Corner Costa Rica', 'Rocca D Evandro Italy',
       'Segataya-Ku Japan', "Kibbutz Mishmar Ha'emek Israel",
       'Fort Lauderdalefort Lauderdale, FL United States',
       'New York City Uzbekistan', 'Castelldfels Spain',
       'Saint Pierre D Oleron France',
       'La Plata, Buenos aires United States', 'Zargoza Spain',
       'Tavagnacco Ud Italy', 'Ballerup, Denmark United States',
       'Amsterdam-Zuid Antigua and Barbuda', 'Maspalmos Spain',
       'Seeblick Ot Wassersuppe Germany',
       'Buenos Aires Argentina, Martinez United States',
       'Louisville Dominican Republic', 'Elmont, Bogota dc United States',
       'West Albury, New South Wales United States',
       'Северо-Западный Административный Окру Russian Federation',
       'Barry D Islemade France', 'Bezirk Spandau Germany',
       'San Esteban De Sasroviras Spain', 'New Territory Hong Kong',
       'Ivanteevka Russian Federation',
       'Tres Arroyos, Buenos aires United States',
       "Pudong New District People's Republic of China",
       'Amsterdam-Oost Antigua and Barbuda', 'Ireland (Irl) Ireland',
       'Mc Farland, WI United States', 'Apo, AP United States',
       'Madrid, Comunidad de Madrid United States',
       'Bleanau Ffestiniog United Kingdom', 'Helsinborg Sweden',
       'Sant Antonino Di Susa Italy', 'Bronx Ireland',
       'Kirk Michael Iceland',
       "Wanjiang District, Dongguan, People's Republic of China",
       'Huntington Stat, NY United States',
       'Saint-Honore-De-Chicoutimi Canada',
       'Glen Huntly, Victoria United States',
       "Nanjingc People's Republic of China", 'Buenos Bires Argentina',
       'Alamosa, Bratislavský kraj United States', 'Singpapore Singapore',
       'Barre, Vaud United States', 'Coalc Australia',
       'Neustift Im Mk. Austria', 'Barre, IllinoisVaud United States',
       "Taichung People's Republic of China", 'Carnikavas Nov. Latvia',
       'Palos Verdes Peninsula, CA United States',
       'Ashby, Buenos aires United States',
       'Stadtbezirke Ix Essen Germany', 'Tsuen Wan Australia',
       'Bjärred United Kingdom', 'Junin, Buenos aires United States',
       'Haarlem, Noord Holland United States',
       "New Taipei People's Republic of China",
       'Dubai, uae United States', 'Vincennesvincennes France',
       'Fotlandsvaag Norway', 'Stetten Akm Germany',
       'Hattorf-Heiligendorf Germany', 'Urb. San Luis, Caracas Venezuela',
       'Saint Isnier France', 'Lonevaag Norway',
       'São Paulo - Brazil Brazil', 'Kitakahei-Cho Japan',
       'Klampenborg, Klampenborg United States', 'Vsters Sweden',
       'Saline Vanuatu', 'Wassenaar Antigua and Barbuda',
       'Blaricum Antigua and Barbuda',
       'Croton On Hudso, NY United States',
       'Minneapolis, Jonkopings lan United States',
       "Hsinchu People's Republic of China", 'Kristansand Norway',
       'Hannaton Israel', 'Hastings On Hud, NY United States',
       'Briarcliff Mano, NY United States', 'Villette D Anthon France',
       'La Chaux-De-Fonds Liechtenstein',
       'Norwalk, ConnecticutNorwalk United States',
       'Haupauge, NY United States',
       'Bezirk Tempelhof-Schöneberg Germany', 'Adachiku Japan',
       'Le Cannet, Alpes Maritimes United States',
       'Great Nck Plz, NY United States', 'Townsead, DE United States',
       'Long Island Cit, NY United States',
       'South Pomfret, South Australia United States',
       'Torslanda, Torslanda United States', 'Reihertshausen Germany',
       'Campton, Victoria United States',
       'Santiago De Los Caballeros Republica Dominicana Dominican Republic',
       "Pukouqu People's Republic of China", 'South Coast Metro Austria',
       'Osteras, Osteras United States', 'Neukirchen Bei Lambch Austria',
       'Canberra, ArkansasACT United States',
       'Nr Bradford United Kingdom', 'Liege, Liege United States',
       "Hsinchu County People's Republic of China",
       'Vrsac, Vrsac United States',
       "Kaohsiung City People's Republic of China", 'Bangkoknoi Thailand',
       'Hockessin, DE United States',
       'Jersey City, New JerseJ United States', 'Belo Horizone Brazil',
       "Kaohsiung People's Republic of China", 'Kecway Halim Indonesia',
       'Boksburg, Gauteng United States', 'Hampton, Vic United States',
       'Prishtina, Kosovo United States', 'Bouskoura France',
       'Hamme Denmark', 'Khuder Soum Mongolia', 'Saint-Herblains France',
       'New York, État de New York United States', 'Vitacura Chad',
       'Johannesburg, Missouriteng United States',
       'Distrito Nacional, Santo Domingo United States',
       'East Waterboro, QLD United States',
       "Guishan Dist. People's Republic of China",
       'Kyoto Mukoucity Japan', 'New York, New YorkNY United States',
       "Kaohsung People's Republic of China",
       'Ulaanbaatar, Bayanzurkh district United States',
       "Taichung City People's Republic of China",
       'Neufgrange French Polynesia', 'Pratovecchiostia Italy',
       'Northampton, FloridaAuckland United States',
       'Frederiksberg, Denmark United States',
       'Bezirk Steglitz-Zehlendorf Germany',
       'Avant, Harju mk United States', 'Elmhurst Thailand',
       'Yangon Burkina Faso', 'Tokorozawashi Japan', 'Mahammedia Morocco',
       'Staten Island Eswatini', 'Hastings-On-Hud, NY United States',
       'Wakefield, Antwerp United States',
       'Beersel, Beersel United States',
       'Blue Springs, italy United States',
       "Fuoshan People's Republic of China",
       'Knokke, West-Vlaanderen United States', 'Commungny Switzerland',
       'Republica Dominicada Dominican Republic',
       'Buenos Aires Antigua and Barbuda', 'Ampher Meung Thailand',
       'Celje, Slovenija United States',
       'North Brunswick, NJ United States',
       "Sanxia Dist., New Taipei City People's Republic of China",
       'Tannanarivo Madagascar', 'Sant Vicen Dels Horts Spain',
       'New Rochelle, New YorkNY United States',
       'Provo, UtahT United States', 'San Pedro, Garza Garcia Mexico',
       'Bezirk Charlottenburg-Wilmersdorf Germany',
       'Isle Of Harris United Kingdom',
       'Newark Nj, Nova JerseyNewark United States',
       'Foligno, Italia/perugia United States', 'Malbourne Australia',
       'Corroy Le Grand, Corroy le Grand United States',
       'Vila Mascote Brazil', 'Guatemala, Ciudad Guatemala United States',
       'Illnau-Effretikon Liechtenstein', 'Chontenay Sur Conie France',
       'Leiderdorp Antigua and Barbuda',
       'Amsterdam-West Antigua and Barbuda', 'Monrterrey Mexico',
       'Luthvle Timon, MD United States', 'Fukuishi Japan',
       'Cassano D. Adda Italy', 'Foligno, Perugia United States',
       'Schreventeich - Hasseldieksdamm De Schreventeich Germany',
       'St Pierre De Clage Switzerland', 'Fotlandsvg Norway',
       'Beograd, Cukarica United States',
       'Ljubljana, Slovenia United States', 'Bouskoura Casablanca France',
       'Vaerloese, Hareskovby United States',
       "Eyguières, Provence-Alpes-Côte d'Azur United States",
       'Arue - Tahiti French Polynesia', 'La Mezieze France',
       'Bezirk Moabit Germany', 'Hoofddorp Antigua and Barbuda',
       'New Market, MarylandMD United States', 'Bangkokyai Thailand',
       'Gyqr Hungary', 'Udine, Friuli-Venezia Giulia United States',
       'Aarsta Sweden', 'Dedham, New South Wales United States',
       'Bondi Junction, NSW United States', 'Londond United Kingdom',
       'Cape Town, western cape United States',
       'Guarenas, Miranda United States', 'Canton, Gauteng United States',
       'Locust Grove Netherlands', 'Etrembier France',
       'Alloway, western cape United States',
       'The Hague Antigua and Barbuda', 'Badin, Madrid United States',
       'Rijswijk Antigua and Barbuda', 'Steffisburg, Bern United States',
       'Saveneta Aruba', 'Bnigen Bei Interlaken Switzerland',
       'Lyonyon France', 'Northeast Carrollton Switzerland',
       'Romaroma Italy', 'Villigen, Aargau United States',
       "Zhubei City, Hsinchu County People's Republic of China",
       'San Mateo Tlaltenango, Ciudad de MéxicoF United States',
       'Empoli, firenze United States', 'Ruda (Ud) Italy',
       'San Pedro, Garza Garcia. Nl Mexico',
       'Oslo, Akershus United States', 'Medelllin Colombia',
       'Neuilly-Sur-Seineeuilly Sur Seine France',
       'Croudace Bay, New South Wales United States', 'Bangpli Thailand',
       'San Fancisco 2 Ríos Costa Rica', 'Amsterdam Antigua and Barbuda',
       'Hasbrouck Heigh, NJ United States', 'Bfpo2 United Kingdom',
       'Humlebaek, Denmark United States',
       'Chácara Santo Antônio (Zona Sul) Brazil',
       'Yorktown Height, NY United States',
       'Sunnysisde, NY United States',
       'San Pedro Sula, cortes United States',
       'New Millport, Bromma United States', 'Omersviller France',
       'La Tahona Golf Club Uruguay', 'Chiswicklondon United Kingdom',
       'Bougueanis France', "Moscow Democratic People's Rep. Korea",
       'Comune Di Castelfranco Emilia Italy', 'Ashton Heights Austria',
       'Whangarei, northland United States',
       'Saint Louis, Hessen United States',
       'Peterboroughbaston United Kingdom', 'Hamburg Andorra',
       'Drancy Antarctica', 'Bangsaothong Thailand',
       'Floral Park, Colombia United States',
       'Uniondale, riyadh United States',
       'Las Palmas - Islas Canarias Spain',
       'Bienrode-Waggum-Bevenrode Germany',
       'Bronx, État de New York United States',
       'Te Awamutu, Waikato United States',
       'Nara-Shi, Nara-Ken United States', 'Snaoya Norway',
       'Rambouilllet France',
       'Condomínio Chácaras Do Alto Da Nova Campinas Brazil',
       'Bezirk Treptow-Köpenick Germany', 'Johanneburg South Africa',
       'Duncanville, Paris United States', 'Behren Les Forbach Germany',
       'Fushe Kosove, Kosovo United States',
       'Charles City, Tijuana United States',
       'Kuesnacht, Zurich United States', 'Möhringenstuttgart Germany',
       'Mid-Level Hong Kong', 'Hamburg-Nordhamburg Germany',
       'Rowe, Baerum United States', 'Waldenburg Sweden',
       'Astoria, New YorkNY United States', 'New Yor, NY United States',
       'Great Neck Italy', 'Greenvale, Vic United States',
       'Tananarivo Madagascar', 'Odrathzeim France',
       'Allen, Ile-de-France United States',
       'Berhren Les Forbach Germany',
       'Nagoya-Shi, Aichi-Ken United States',
       'Ituzaingo, Buenos aires United States', 'Russee - Hammer Germany',
       'Las Condes, Santiago Metropolitan Region United States',
       "Shagnhai People's Republic of China",
       'Oakland, CaliforniaCA United States',
       'Saint Syr Sur Rhone France', 'Gany Tikva Israel',
       'Aosta Italy Italy', 'Residencial Seis (Alphaville) Brazil',
       'Prishtina, Kosova United States', 'St-Sauveur-Des-Monts Canada',
       'Hong Kong, New Territories United States',
       'Lillehammer, Norway United States', 'Bronbron France',
       'København Nv Denmark', 'Reykjavík, Seltjarnarnes United States',
       'Capital Federal, Ciudad de BUenos Aires United States',
       'Capital, Santiago del Estero United States', 'Clazac France',
       'Leciestershire United Kingdom',
       'Bradfield Reading United Kingdom',
       'Portwashington, NY United States',
       'Pt Pleas Bch, NJ United States', 'Wimbledon Venezuela',
       'Mexico City Mayotte', 'Naarden Antigua and Barbuda',
       'Brighton East, Victoria United States',
       'New Kensington, PennsylvaniaPa United States',
       'Clayton, Italia United States', 'Stafford, England United States',
       'Boston, MassachusettsB United States',
       'Willemstad Antigua and Barbuda', 'Panamam Panama',
       'Seftigen Liechtenstein', 'Clearwater Bay Hong Kong',
       'Dorchestr Ctr, MA United States', 'Miami Beach, NY United States',
       'South Plainfiel, NJ United States',
       'Northampton, Auckland United States', 'Fpo, AE United States',
       'South Windham South Africa', 'Glasser, NJ United States',
       'Hamilton, Waikato United States', 'Kirtyat Ono Israel',
       'Deventer Antigua and Barbuda', 'Quto Ecuador',
       'Springfield Grd, NY United States',
       'Neustadt Am Rübenbergeneustadt Germany',
       'Provincetownemaastricht Netherlands', 'Guthenburg Sweden',
       'Bezirk Bergedorf  Hamburg Germany',
       'Antwerpen, Anterpen United States', 'Guatema Guatemala',
       'Sydney, New South Wales United States', 'Linkping Sweden',
       'Omalley, ACT United States', 'Bezirk Reinickendorf Germany',
       'Paducah, SORIA United States', 'Piton Saint-Leu France',
       'Mc Kean, PA United States', 'Miramont D Astarac France',
       'Plainwell, Maine et Loire United States',
       'Ecublens Liechtenstein', 'Hopewell Juncti, NY United States',
       "Ｈｏｎｇ\u3000Ｋｏｎｇ People's Republic of China", 'Buccinaso Italy',
       'Sant Petesburg Russian Federation', 'Castroville Uzbekistan',
       "Shangahai People's Republic of China", 'Casablaca Morocco',
       'Pq Res Aquarius Brazil', 'Ceby City Philippines',
       'Untergiesing-Harlachingmnchen Germany', 'Skopje Norway',
       'Kew Gardens Hil, NY United States',
       'N. Valley Strea, NY United States', 'Sparrta, NJ United States',
       'Bellevue Hill, NSW United States',
       'Eltham, Victoria United States', 'Minot, Gauteng United States',
       'Grand Cayman Canada', 'Dorforf Liechtenstein',
       'Longuiville Australia', 'Nes Ziyona Israel',
       'Chicago, Illinois [IL] United States',
       'East Dover, Famagusta United States',
       'Kroonstad, Free state United States',
       'Geraardsbergen, Oost Vlaanderen United States',
       'General Pico, La Pampa, Argentina Argentina',
       'Apeldoorn Noord-Oost Netherlands',
       'Manahawkin, Bolivar United States',
       'Bologna, Emilia-Romagna United States',
       'New York, Thailand United States',
       'Sebago Lake, QLD United States', 'Margherita Di Savoia Jamaica',
       'Cumming Italy', 'Herewegwijk En Helpman Netherlands',
       'New Rochelle, New orkN United States', 'Bladelbladel Netherlands',
       'Dublin, Dun Laoghaire United States', 'S.M. De Tucuman Argentina',
       'Stadtbezirke Iv Germany',
       'U.S Virgin Island, St. Thomas United States',
       'Brain Sur L Authion France',
       'Longs, South CarolinaJeff Leake United States',
       'Melbounre Australia', 'Salles D Angles France',
       'Montugny Le Bretonneux France', 'Columbia, Varese United States',
       'Numansdorp Antigua and Barbuda',
       'Princeton Jct, NJ United States', 'Middx United Kingdom',
       'Vandoncourt, FRANCE United States',
       'Comune Di Castelfranco Veneto Italy',
       'Sparreholm, Södermanlands län United States',
       'Dardillydardilly France',
       'Sao Bernardo Do Campo, São Paulo United States',
       'Barnegat, western cape United States',
       'Longe Ville Les Metz France', 'Mc Gregor, TX United States',
       'Bezirk Neukölln Germany',
       'Rancho Cordova, CaliforniaAndrei United States',
       'Manhattan, État de New York United States', 'Aracaju Botswana',
       'Raynes Arkp United Kingdom', 'Rittenhouse Square Belgium',
       'Erlangen, Germany United States', 'Higasikanbara Japan',
       'Foxboro, New YorkNSW United States',
       'San Francisco, Ile de France United States',
       'Saint Romain Au Mont D Or France',
       'Briar Hill, Victoria United States',
       'Hong Kong, CHINA United States',
       'Nottingham, KwaZulu Natal United States',
       'Eindhoven Antigua and Barbuda', 'Kng Of Prussa, PA United States',
       'Campinas, Sao Paulo United States', 'Hellerup, NA United States',
       'Rosino Bulgaria', 'North Chatham, Antwerpen United States',
       'Johannesburg, Gauteng United States',
       'De Veenhoop Antigua and Barbuda', 'Hertzelia Israel',
       'Wijk Bij Duurstede Antigua and Barbuda',
       "Hatdtan District People's Republic of China",
       "Taiper City People's Republic of China",
       'South Ozone Par, NY United States', 'Setonai-Shi Japan',
       'Aran-Villette/Grandvaux Liechtenstein', 'Lima18 Peru',
       'Frederiksberg, Frederiksberg United States',
       'Quezon City, Manila United States',
       'Arnada, Metro Manila United States', 'Seuzach Liechtenstein',
       'Rockville Centr, NY United States', 'New Yurk, NY United States',
       'Prverenges Switzerland', "Beijjing People's Republic of China",
       'Hainichen/Ot Bockendorf Germany',
       'Chatuchak, Bangkok United States', 'Tucson Germany',
       'Mesa Norway', 'Finglas North, County Dublin United States',
       'Bahia Blanca, Buenos aires United States',
       'Darfo Baorio Terme Italy', 'Barrington, Vic United States',
       'Saikung Hong Kong', 'Palmyra, Western Australia United States',
       'East Freetown Italy', 'Apo, Troms United States',
       'New Territories, Sham Tseng United States', 'Mimato-Ku Japan',
       'Bandolbandol France', 'Bezirk Marzahn-Hellersdorf Germany',
       'Oakleigh, Victoria United States',
       'Caba Bs As Argentina Argentina',
       'Hvittingfoss, Norway United States',
       'Queens, New York [NY] United States',
       'Whitlwy Bay United Kingdom',
       'Gam, Ciudad de Mexico United States',
       'St.Peteresburg Russian Federation',
       'Punaauia - Tahiti French Polynesia',
       'Cabo Rojo Northern Mariana Islands',
       'Weymouth, Gauteng United States',
       'Bezirk Friedrichshain-Kreuzberg Germany',
       'Brooklyln, NY United States', 'Gratta Terme (Fc) Italy',
       'Vessy, Geneve United States', 'Bangkok, Bangkok United States',
       'San Fracisco De Campeche Mexico',
       "Nr Bishop's Stortford United Kingdom",
       'Severna Parkseverna Park, MD United States',
       'Rignano Sul Arno Italy', 'Kasugashi Japan',
       'San Antonio, TexasTx United States', 'Beratzhausen Aruba',
       'Tampa, Nordrhein-Westfalen United States',
       'Northampton, Auckland City United States', 'Guayllabamna Ecuador',
       'Yuenlong Hong Kong',
       'Washington, New JerseyWashington United States',
       'Kopavogi, Iceland United States', 'Salzano Venice Italy',
       'Stavanger, Hafrsfjord United States', 'Eagleville Italy',
       'Palmerston North, MANAWATU United States',
       'Bellingham, Norway United States', 'Cfar Bialik Israel',
       'Beek - Ubergen Netherlands', 'Monclair, NJ United States',
       'Mooloolaba, Queensland United States',
       "Banqiao Dist People's Republic of China",
       'Ikoyi, Lagos United States',
       'San Clemente, Californiac United States',
       'Durham, England United States', 'Nøtterøy, Norway United States',
       'Guayaqsuil Ecuador', 'Saint Louis, MissouriMO United States',
       'Esbo, Finland United States', 'Kualalumpur Malaysia',
       'Apo, Oost Vlaanderen United States',
       'Worcester, Buenos aires United States',
       'Framingham, Metro Manila United States',
       'Bodegraven, Holandia Południowa United States',
       'Fort Worth, UNITED STATES United States',
       'Amphoe Dan Khun Thot Thailand', 'Hungtington, NY United States',
       'Taguig City, Metro Manila United States', 'Thonburi Thailand',
       'Wishart Australia', 'Oadby United Kingdom', 'Pollestres France',
       "Clearwater Bay, Sai Kung People's Republic of China",
       'Cossato, Biella United States',
       'Manchester, Connecticutt United States',
       'Cumberlnd Ctr, ME United States', 'Alpharetta Indonesia',
       'Las Pinas, Metro Manila United States',

In [17]:
query_df = pd.DataFrame(address_list)
query_df.to_csv('..00_data/geodata/list.csv')

### Commence geocoding

In [18]:
# set up the geocoder

locator = Nominatim(user_agent="myGeocoder")
geocode = RateLimiter(locator.geocode, min_delay_seconds=1)

In [19]:
location_dict = {}
problem_locations = []
counter = 0
goal = len(address_list)

for address in address_list:
    counter += 1
    try:
        location_result = geocode(address)
        if location_result == None:
            problem_locations.append(address)
            print("{} of {}. No location found for {}.".format(counter, goal, address))
        else:
            location_dict[address] = geocode(address)
            print("{} of {}. Found location for {}.".format(counter, goal, address))
    except:
        problem_locations.append(address)
        print("{} of {}. No location found for {}.".format(counter, goal, address))

1 of 535. No location found for Kapkitony Kenya.
2 of 535. No location found for New Taipei City People's Republic of China.
3 of 535. No location found for O Fallon, MO United States.
4 of 535. No location found for Chesitek Kenya.
5 of 535. Found location for nan.
6 of 535. No location found for Hsinchu City People's Republic of China.
7 of 535. No location found for Fpo, AP United States.
8 of 535. No location found for København Sv Denmark.
9 of 535. No location found for Miaoli County People's Republic of China.
10 of 535. No location found for Loenen Gld Netherlands.
11 of 535. No location found for Seoul, Mapo-gu United States.
12 of 535. No location found for Nakorn Ratchasima Thailand.
13 of 535. No location found for North Plainfiel, NJ United States.
14 of 535. No location found for Steeplechase Corner Costa Rica.
15 of 535. No location found for Rocca D Evandro Italy.
16 of 535. No location found for Segataya-Ku Japan.
17 of 535. No location found for Kibbutz Mishmar Ha'emek Israel.
18 of 535. No location found for Fort Lauderdalefort Lauderdale, FL United States.
19 of 535. No location found for New York City Uzbekistan.
20 of 535. No location found for Castelldfels Spain.
21 of 535. No location found for Saint Pierre D Oleron France.
22 of 535. No location found for La Plata, Buenos aires United States.
23 of 535. No location found for Zargoza Spain.
24 of 535. No location found for Tavagnacco Ud Italy.
25 of 535. No location found for Ballerup, Denmark United States.
26 of 535. No location found for Amsterdam-Zuid Antigua and Barbuda.
27 of 535. No location found for Maspalmos Spain.
28 of 535. No location found for Seeblick Ot Wassersuppe Germany.
29 of 535. No location found for Buenos Aires Argentina, Martinez United States.
30 of 535. No location found for Louisville Dominican Republic.
31 of 535. No location found for Elmont, Bogota dc United States.
32 of 535. No location found for West Albury, New South Wales United States.
33 of 535. No location found for Северо-Западный Административный Окру Russian Federation.
34 of 535. No location found for Barry D Islemade France.
35 of 535. No location found for Bezirk Spandau Germany.
36 of 535. No location found for San Esteban De Sasroviras Spain.
37 of 535. No location found for New Territory Hong Kong.
38 of 535. No location found for Ivanteevka Russian Federation.
39 of 535. No location found for Tres Arroyos, Buenos aires United States.
40 of 535. No location found for Pudong New District People's Republic of China.
41 of 535. No location found for Amsterdam-Oost Antigua and Barbuda.
42 of 535. No location found for Ireland (Irl) Ireland.
43 of 535. No location found for Mc Farland, WI United States.
44 of 535. No location found for Apo, AP United States.
45 of 535. No location found for Madrid, Comunidad de Madrid United States.
46 of 535. No location found for Bleanau Ffestiniog United Kingdom.
47 of 535. No location found for Helsinborg Sweden.
48 of 535. No location found for Sant Antonino Di Susa Italy.
49 of 535. No location found for Bronx Ireland.
50 of 535. No location found for Kirk Michael Iceland.
51 of 535. No location found for Wanjiang District, Dongguan, People's Republic of China.
52 of 535. No location found for Huntington Stat, NY United States.
53 of 535. No location found for Saint-Honore-De-Chicoutimi Canada.
54 of 535. No location found for Glen Huntly, Victoria United States.
55 of 535. No location found for Nanjingc People's Republic of China.
56 of 535. No location found for Buenos Bires Argentina.
57 of 535. No location found for Alamosa, Bratislavský kraj United States.
58 of 535. No location found for Singpapore Singapore.
59 of 535. No location found for Barre, Vaud United States.
60 of 535. No location found for Coalc Australia.
61 of 535. No location found for Neustift Im Mk. Austria.
62 of 535. No location found for Barre, IllinoisVaud United States.
63 of 535. No location found for Taichung People's Republic of China.
64 of 535. No location found for Carnikavas Nov. Latvia.
65 of 535. No location found for Palos Verdes Peninsula, CA United States.
66 of 535. No location found for Ashby, Buenos aires United States.
67 of 535. No location found for Stadtbezirke Ix Essen Germany.
68 of 535. No location found for Tsuen Wan Australia.
69 of 535. No location found for Bjärred United Kingdom.
70 of 535. No location found for Junin, Buenos aires United States.
71 of 535. No location found for Haarlem, Noord Holland United States.
72 of 535. No location found for New Taipei People's Republic of China.
73 of 535. No location found for Dubai, uae United States.
74 of 535. No location found for Vincennesvincennes France.
75 of 535. No location found for Fotlandsvaag Norway.
76 of 535. No location found for Stetten Akm Germany.
77 of 535. No location found for Hattorf-Heiligendorf Germany.
78 of 535. No location found for Urb. San Luis, Caracas Venezuela.
79 of 535. No location found for Saint Isnier France.
80 of 535. No location found for Lonevaag Norway.
81 of 535. No location found for São Paulo - Brazil Brazil.
82 of 535. No location found for Kitakahei-Cho Japan.
83 of 535. No location found for Klampenborg, Klampenborg United States.
84 of 535. No location found for Vsters Sweden.
85 of 535. No location found for Saline Vanuatu.
86 of 535. No location found for Wassenaar Antigua and Barbuda.
87 of 535. No location found for Blaricum Antigua and Barbuda.
88 of 535. No location found for Croton On Hudso, NY United States.
89 of 535. No location found for Minneapolis, Jonkopings lan United States.
90 of 535. No location found for Hsinchu People's Republic of China.
91 of 535. No location found for Kristansand Norway.
92 of 535. No location found for Hannaton Israel.
93 of 535. No location found for Hastings On Hud, NY United States.
94 of 535. No location found for Briarcliff Mano, NY United States.
95 of 535. No location found for Villette D Anthon France.
96 of 535. No location found for La Chaux-De-Fonds Liechtenstein.
97 of 535. No location found for Norwalk, ConnecticutNorwalk United States.
98 of 535. No location found for Haupauge, NY United States.
99 of 535. No location found for Bezirk Tempelhof-Schöneberg Germany.
100 of 535. No location found for Adachiku Japan.
101 of 535. No location found for Le Cannet, Alpes Maritimes United States.
102 of 535. No location found for Great Nck Plz, NY United States.
103 of 535. No location found for Townsead, DE United States.
104 of 535. No location found for Long Island Cit, NY United States.
105 of 535. No location found for South Pomfret, South Australia United States.
106 of 535. No location found for Torslanda, Torslanda United States.
107 of 535. No location found for Reihertshausen Germany.
108 of 535. No location found for Campton, Victoria United States.
109 of 535. No location found for Santiago De Los Caballeros Republica Dominicana Dominican Republic.
110 of 535. No location found for Pukouqu People's Republic of China.
111 of 535. No location found for South Coast Metro Austria.
112 of 535. No location found for Osteras, Osteras United States.
113 of 535. No location found for Neukirchen Bei Lambch Austria.
114 of 535. No location found for Canberra, ArkansasACT United States.
115 of 535. No location found for Nr Bradford United Kingdom.
116 of 535. No location found for Liege, Liege United States.
117 of 535. No location found for Hsinchu County People's Republic of China.
118 of 535. No location found for Vrsac, Vrsac United States.
119 of 535. No location found for Kaohsiung City People's Republic of China.
120 of 535. No location found for Bangkoknoi Thailand.
121 of 535. No location found for Hockessin, DE United States.
122 of 535. No location found for Jersey City, New JerseJ United States.
123 of 535. No location found for Belo Horizone Brazil.
124 of 535. No location found for Kaohsiung People's Republic of China.
125 of 535. No location found for Kecway Halim Indonesia.
126 of 535. No location found for Boksburg, Gauteng United States.
127 of 535. No location found for Hampton, Vic United States.
128 of 535. No location found for Prishtina, Kosovo United States.
129 of 535. No location found for Bouskoura France.

130 of 535. No location found for Hamme Denmark.
131 of 535. No location found for Khuder Soum Mongolia.
132 of 535. No location found for Saint-Herblains France.
133 of 535. No location found for New York, État de New York United States.
134 of 535. No location found for Vitacura Chad.
135 of 535. No location found for Johannesburg, Missouriteng United States.
136 of 535. No location found for Distrito Nacional, Santo Domingo United States.
137 of 535. No location found for East Waterboro, QLD United States.
138 of 535. No location found for Guishan Dist. People's Republic of China.
139 of 535. No location found for Kyoto Mukoucity Japan.
140 of 535. No location found for New York, New YorkNY United States.
141 of 535. No location found for Kaohsung People's Republic of China.
142 of 535. No location found for Ulaanbaatar, Bayanzurkh district United States.
143 of 535. No location found for Taichung City People's Republic of China.
144 of 535. No location found for Neufgrange French Polynesia.
145 of 535. No location found for Pratovecchiostia Italy.
146 of 535. No location found for Northampton, FloridaAuckland United States.
147 of 535. No location found for Frederiksberg, Denmark United States.
148 of 535. No location found for Bezirk Steglitz-Zehlendorf Germany.
149 of 535. No location found for Avant, Harju mk United States.
150 of 535. No location found for Elmhurst Thailand.
151 of 535. No location found for Yangon Burkina Faso.
152 of 535. No location found for Tokorozawashi Japan.
153 of 535. No location found for Mahammedia Morocco.
154 of 535. No location found for Staten Island Eswatini.
155 of 535. No location found for Hastings-On-Hud, NY United States.
156 of 535. No location found for Wakefield, Antwerp United States.
157 of 535. No location found for Beersel, Beersel United States.
158 of 535. No location found for Blue Springs, italy United States.
159 of 535. No location found for Fuoshan People's Republic of China.
160 of 535. No location found for Knokke, West-Vlaanderen United States.
161 of 535. No location found for Commungny Switzerland.
162 of 535. No location found for Republica Dominicada Dominican Republic.
163 of 535. No location found for Buenos Aires Antigua and Barbuda.
164 of 535. No location found for Ampher Meung Thailand.
165 of 535. No location found for Celje, Slovenija United States.
166 of 535. No location found for North Brunswick, NJ United States.
167 of 535. No location found for Sanxia Dist., New Taipei City People's Republic of China.
168 of 535. No location found for Tannanarivo Madagascar.
169 of 535. No location found for Sant Vicen Dels Horts Spain.
170 of 535. No location found for New Rochelle, New YorkNY United States.
171 of 535. No location found for Provo, UtahT United States.
172 of 535. No location found for San Pedro, Garza Garcia Mexico.
173 of 535. No location found for Bezirk Charlottenburg-Wilmersdorf Germany.
174 of 535. No location found for Isle Of Harris United Kingdom.
175 of 535. No location found for Newark Nj, Nova JerseyNewark United States.
176 of 535. No location found for Foligno, Italia/perugia United States.
177 of 535. No location found for Malbourne Australia.
178 of 535. No location found for Corroy Le Grand, Corroy le Grand United States.
179 of 535. No location found for Vila Mascote Brazil.
180 of 535. No location found for Guatemala, Ciudad Guatemala United States.
181 of 535. No location found for Illnau-Effretikon Liechtenstein.
182 of 535. No location found for Chontenay Sur Conie France.
183 of 535. No location found for Leiderdorp Antigua and Barbuda.
184 of 535. No location found for Amsterdam-West Antigua and Barbuda.
185 of 535. No location found for Monrterrey Mexico.
186 of 535. No location found for Luthvle Timon, MD United States.
187 of 535. No location found for Fukuishi Japan.
188 of 535. No location found for Cassano D. Adda Italy.
189 of 535. No location found for Foligno, Perugia United States.
190 of 535. No location found for Schreventeich - Hasseldieksdamm De Schreventeich Germany.
191 of 535. No location found for St Pierre De Clage Switzerland.
192 of 535. No location found for Fotlandsvg Norway.
193 of 535. No location found for Beograd, Cukarica United States.
194 of 535. No location found for Ljubljana, Slovenia United States.
195 of 535. No location found for Bouskoura Casablanca France.
196 of 535. No location found for Vaerloese, Hareskovby United States.
197 of 535. No location found for Eyguières, Provence-Alpes-Côte d'Azur United States.
198 of 535. No location found for Arue - Tahiti French Polynesia.
199 of 535. No location found for La Mezieze France.
200 of 535. No location found for Bezirk Moabit Germany.
201 of 535. No location found for Hoofddorp Antigua and Barbuda.
202 of 535. No location found for New Market, MarylandMD United States.
203 of 535. No location found for Bangkokyai Thailand.
204 of 535. No location found for Gyqr Hungary.
205 of 535. No location found for Udine, Friuli-Venezia Giulia United States.
206 of 535. No location found for Aarsta Sweden.
207 of 535. No location found for Dedham, New South Wales United States.
208 of 535. No location found for Bondi Junction, NSW United States.
209 of 535. No location found for Londond United Kingdom.
210 of 535. No location found for Cape Town, western cape United States.
211 of 535. No location found for Guarenas, Miranda United States.
212 of 535. No location found for Canton, Gauteng United States.
213 of 535. No location found for Locust Grove Netherlands.
214 of 535. No location found for Etrembier France.
215 of 535. No location found for Alloway, western cape United States.
216 of 535. No location found for The Hague Antigua and Barbuda.
217 of 535. No location found for Badin, Madrid United States.
218 of 535. No location found for Rijswijk Antigua and Barbuda.
219 of 535. No location found for Steffisburg, Bern United States.
220 of 535. No location found for Saveneta Aruba.
221 of 535. No location found for Bnigen Bei Interlaken Switzerland.
222 of 535. No location found for Lyonyon France.
223 of 535. No location found for Northeast Carrollton Switzerland.
224 of 535. No location found for Romaroma Italy.
225 of 535. No location found for Villigen, Aargau United States.
226 of 535. No location found for Zhubei City, Hsinchu County People's Republic of China.
227 of 535. No location found for San Mateo Tlaltenango, Ciudad de MéxicoF United States.
228 of 535. No location found for Empoli, firenze United States.
229 of 535. No location found for Ruda (Ud) Italy.
230 of 535. No location found for San Pedro, Garza Garcia. Nl Mexico.
231 of 535. No location found for Oslo, Akershus United States.
232 of 535. No location found for Medelllin Colombia.
233 of 535. No location found for Neuilly-Sur-Seineeuilly Sur Seine France.
234 of 535. No location found for Croudace Bay, New South Wales United States.
235 of 535. No location found for Bangpli Thailand.
236 of 535. No location found for San Fancisco 2 Ríos Costa Rica.
237 of 535. No location found for Amsterdam Antigua and Barbuda.
238 of 535. No location found for Hasbrouck Heigh, NJ United States.
239 of 535. No location found for Bfpo2 United Kingdom.
240 of 535. No location found for Humlebaek, Denmark United States.
241 of 535. No location found for Chácara Santo Antônio (Zona Sul) Brazil.
242 of 535. No location found for Yorktown Height, NY United States.
243 of 535. No location found for Sunnysisde, NY United States.
244 of 535. No location found for San Pedro Sula, cortes United States.
245 of 535. No location found for New Millport, Bromma United States.
246 of 535. No location found for Omersviller France.
247 of 535. No location found for La Tahona Golf Club Uruguay.
248 of 535. No location found for Chiswicklondon United Kingdom.
249 of 535. No location found for Bougueanis France.
250 of 535. No location found for Moscow Democratic People's Rep. Korea.
251 of 535. No location found for Comune Di Castelfranco Emilia Italy.
252 of 535. No location found for Ashton Heights Austria.
253 of 535. No location found for Whangarei, northland United States.
254 of 535. No location found for Saint Louis, Hessen United States.

255 of 535. No location found for Peterboroughbaston United Kingdom.
256 of 535. No location found for Hamburg Andorra.
257 of 535. No location found for Drancy Antarctica.
258 of 535. No location found for Bangsaothong Thailand.
259 of 535. No location found for Floral Park, Colombia United States.
260 of 535. No location found for Uniondale, riyadh United States.
261 of 535. No location found for Las Palmas - Islas Canarias Spain.
262 of 535. No location found for Bienrode-Waggum-Bevenrode Germany.
263 of 535. No location found for Bronx, État de New York United States.
264 of 535. No location found for Te Awamutu, Waikato United States.
265 of 535. No location found for Nara-Shi, Nara-Ken United States.
266 of 535. No location found for Snaoya Norway.
267 of 535. No location found for Rambouilllet France.
268 of 535. No location found for Condomínio Chácaras Do Alto Da Nova Campinas Brazil.
269 of 535. No location found for Bezirk Treptow-Köpenick Germany.
270 of 535. No location found for Johanneburg South Africa.
271 of 535. No location found for Duncanville, Paris United States.
272 of 535. No location found for Behren Les Forbach Germany.
273 of 535. No location found for Fushe Kosove, Kosovo United States.
274 of 535. No location found for Charles City, Tijuana United States.
275 of 535. No location found for Kuesnacht, Zurich United States.
276 of 535. No location found for Möhringenstuttgart Germany.
277 of 535. No location found for Mid-Level Hong Kong.
278 of 535. No location found for Hamburg-Nordhamburg Germany.
279 of 535. No location found for Rowe, Baerum United States.
280 of 535. No location found for Waldenburg Sweden.
281 of 535. No location found for Astoria, New YorkNY United States.
282 of 535. No location found for New Yor, NY United States.
283 of 535. No location found for Great Neck Italy.
284 of 535. No location found for Greenvale, Vic United States.
285 of 535. No location found for Tananarivo Madagascar.
286 of 535. No location found for Odrathzeim France.
287 of 535. No location found for Allen, Ile-de-France United States.
288 of 535. No location found for Berhren Les Forbach Germany.
289 of 535. No location found for Nagoya-Shi, Aichi-Ken United States.
290 of 535. No location found for Ituzaingo, Buenos aires United States.
291 of 535. No location found for Russee - Hammer Germany.
292 of 535. No location found for Las Condes, Santiago Metropolitan Region United States.
293 of 535. No location found for Shagnhai People's Republic of China.
294 of 535. No location found for Oakland, CaliforniaCA United States.
295 of 535. No location found for Saint Syr Sur Rhone France.
296 of 535. No location found for Gany Tikva Israel.
297 of 535. No location found for Aosta Italy Italy.
298 of 535. No location found for Residencial Seis (Alphaville) Brazil.
299 of 535. No location found for Prishtina, Kosova United States.
300 of 535. No location found for St-Sauveur-Des-Monts Canada.
301 of 535. No location found for Hong Kong, New Territories United States.
302 of 535. No location found for Lillehammer, Norway United States.
303 of 535. No location found for Bronbron France.
304 of 535. No location found for København Nv Denmark.
305 of 535. No location found for Reykjavík, Seltjarnarnes United States.
306 of 535. No location found for Capital Federal, Ciudad de BUenos Aires United States.
307 of 535. No location found for Capital, Santiago del Estero United States.
308 of 535. No location found for Clazac France.
309 of 535. No location found for Leciestershire United Kingdom.
310 of 535. No location found for Bradfield Reading United Kingdom.
311 of 535. No location found for Portwashington, NY United States.
312 of 535. No location found for Pt Pleas Bch, NJ United States.
313 of 535. No location found for Wimbledon Venezuela.
314 of 535. No location found for Mexico City Mayotte.
315 of 535. No location found for Naarden Antigua and Barbuda.
316 of 535. No location found for Brighton East, Victoria United States.
317 of 535. No location found for New Kensington, PennsylvaniaPa United States.
318 of 535. No location found for Clayton, Italia United States.
319 of 535. No location found for Stafford, England United States.
320 of 535. No location found for Boston, MassachusettsB United States.
321 of 535. No location found for Willemstad Antigua and Barbuda.
322 of 535. No location found for Panamam Panama.
323 of 535. No location found for Seftigen Liechtenstein.
324 of 535. No location found for Clearwater Bay Hong Kong.
325 of 535. No location found for Dorchestr Ctr, MA United States.
326 of 535. No location found for Miami Beach, NY United States.
327 of 535. No location found for South Plainfiel, NJ United States.
328 of 535. No location found for Northampton, Auckland United States.
329 of 535. No location found for Fpo, AE United States.
330 of 535. No location found for South Windham South Africa.
331 of 535. No location found for Glasser, NJ United States.
332 of 535. No location found for Hamilton, Waikato United States.
333 of 535. No location found for Kirtyat Ono Israel.
334 of 535. No location found for Deventer Antigua and Barbuda.
335 of 535. No location found for Quto Ecuador.
336 of 535. No location found for Springfield Grd, NY United States.
337 of 535. No location found for Neustadt Am Rübenbergeneustadt Germany.
338 of 535. No location found for Provincetownemaastricht Netherlands.
339 of 535. No location found for Guthenburg Sweden.
340 of 535. No location found for Bezirk Bergedorf  Hamburg Germany.
341 of 535. No location found for Antwerpen, Anterpen United States.
342 of 535. No location found for Guatema Guatemala.
343 of 535. No location found for Sydney, New South Wales United States.
344 of 535. No location found for Linkping Sweden.
345 of 535. No location found for Omalley, ACT United States.
346 of 535. No location found for Bezirk Reinickendorf Germany.
347 of 535. No location found for Paducah, SORIA United States.
348 of 535. No location found for Piton Saint-Leu France.
349 of 535. No location found for Mc Kean, PA United States.
350 of 535. No location found for Miramont D Astarac France.
351 of 535. No location found for Plainwell, Maine et Loire United States.
352 of 535. No location found for Ecublens Liechtenstein.
353 of 535. No location found for Hopewell Juncti, NY United States.
354 of 535. No location found for Ｈｏｎｇ　Ｋｏｎｇ People's Republic of China.
355 of 535. No location found for Buccinaso Italy.
356 of 535. No location found for Sant Petesburg Russian Federation.
357 of 535. No location found for Castroville Uzbekistan.
358 of 535. No location found for Shangahai People's Republic of China.
359 of 535. No location found for Casablaca Morocco.
360 of 535. No location found for Pq Res Aquarius Brazil.
361 of 535. No location found for Ceby City Philippines.
362 of 535. No location found for Untergiesing-Harlachingmnchen Germany.
363 of 535. No location found for Skopje Norway.
364 of 535. No location found for Kew Gardens Hil, NY United States.
365 of 535. No location found for N. Valley Strea, NY United States.
366 of 535. No location found for Sparrta, NJ United States.
367 of 535. No location found for Bellevue Hill, NSW United States.
368 of 535. No location found for Eltham, Victoria United States.
369 of 535. No location found for Minot, Gauteng United States.
370 of 535. No location found for Grand Cayman Canada.
371 of 535. No location found for Dorforf Liechtenstein.
372 of 535. No location found for Longuiville Australia.
373 of 535. No location found for Nes Ziyona Israel.
374 of 535. No location found for Chicago, Illinois [IL] United States.
375 of 535. No location found for East Dover, Famagusta United States.
376 of 535. No location found for Kroonstad, Free state United States.
377 of 535. No location found for Geraardsbergen, Oost Vlaanderen United States.
378 of 535. No location found for General Pico, La Pampa, Argentina Argentina.
379 of 535. No location found for Apeldoorn Noord-Oost Netherlands.
380 of 535. No location found for Manahawkin, Bolivar United States.
381 of 535. No location found for Bologna, Emilia-Romagna United States.
382 of 535. No location found for New York, Thailand United States.

383 of 535. No location found for Sebago Lake, QLD United States.
384 of 535. No location found for Margherita Di Savoia Jamaica.
385 of 535. No location found for Cumming Italy.
386 of 535. No location found for Herewegwijk En Helpman Netherlands.
387 of 535. No location found for New Rochelle, New orkN United States.
388 of 535. No location found for Bladelbladel Netherlands.
389 of 535. No location found for Dublin, Dun Laoghaire United States.
390 of 535. No location found for S.M. De Tucuman Argentina.
391 of 535. No location found for Stadtbezirke Iv Germany.
392 of 535. No location found for U.S Virgin Island, St. Thomas United States.
393 of 535. No location found for Brain Sur L Authion France.
394 of 535. No location found for Longs, South CarolinaJeff Leake United States.
395 of 535. No location found for Melbounre Australia.
396 of 535. No location found for Salles D Angles France.
397 of 535. No location found for Montugny Le Bretonneux France.
398 of 535. No location found for Columbia, Varese United States.
399 of 535. No location found for Numansdorp Antigua and Barbuda.
400 of 535. No location found for Princeton Jct, NJ United States.
401 of 535. No location found for Middx United Kingdom.
402 of 535. No location found for Vandoncourt, FRANCE United States.
403 of 535. No location found for Comune Di Castelfranco Veneto Italy.
404 of 535. No location found for Sparreholm, Södermanlands län United States.
405 of 535. No location found for Dardillydardilly France.
406 of 535. No location found for Sao Bernardo Do Campo, São Paulo United States.
407 of 535. No location found for Barnegat, western cape United States.
408 of 535. No location found for Longe Ville Les Metz France.
409 of 535. No location found for Mc Gregor, TX United States.
410 of 535. No location found for Bezirk Neukölln Germany.
411 of 535. No location found for Rancho Cordova, CaliforniaAndrei United States.
412 of 535. No location found for Manhattan, État de New York United States.
413 of 535. No location found for Aracaju Botswana.
414 of 535. No location found for Raynes Arkp United Kingdom.
415 of 535. No location found for Rittenhouse Square Belgium.
416 of 535. No location found for Erlangen, Germany United States.
417 of 535. No location found for Higasikanbara Japan.
418 of 535. No location found for Foxboro, New YorkNSW United States.
419 of 535. No location found for San Francisco, Ile de France United States.
420 of 535. No location found for Saint Romain Au Mont D Or France.
421 of 535. No location found for Briar Hill, Victoria United States.
422 of 535. No location found for Hong Kong, CHINA United States.
423 of 535. No location found for Nottingham, KwaZulu Natal United States.
424 of 535. No location found for Eindhoven Antigua and Barbuda.
425 of 535. No location found for Kng Of Prussa, PA United States.
426 of 535. No location found for Campinas, Sao Paulo United States.
427 of 535. No location found for Hellerup, NA United States.
428 of 535. No location found for Rosino Bulgaria.
429 of 535. No location found for North Chatham, Antwerpen United States.
430 of 535. No location found for Johannesburg, Gauteng United States.
431 of 535. No location found for De Veenhoop Antigua and Barbuda.
432 of 535. No location found for Hertzelia Israel.
433 of 535. No location found for Wijk Bij Duurstede Antigua and Barbuda.
434 of 535. No location found for Hatdtan District People's Republic of China.
435 of 535. No location found for Taiper City People's Republic of China.
436 of 535. No location found for South Ozone Par, NY United States.
437 of 535. No location found for Setonai-Shi Japan.
438 of 535. No location found for Aran-Villette/Grandvaux Liechtenstein.
439 of 535. No location found for Lima18 Peru.
440 of 535. No location found for Frederiksberg, Frederiksberg United States.
441 of 535. No location found for Quezon City, Manila United States.
442 of 535. No location found for Arnada, Metro Manila United States.
443 of 535. No location found for Seuzach Liechtenstein.
444 of 535. No location found for Rockville Centr, NY United States.
445 of 535. No location found for New Yurk, NY United States.
446 of 535. No location found for Prverenges Switzerland.
447 of 535. No location found for Beijjing People's Republic of China.
448 of 535. No location found for Hainichen/Ot Bockendorf Germany.
449 of 535. No location found for Chatuchak, Bangkok United States.
450 of 535. No location found for Tucson Germany.
451 of 535. No location found for Mesa Norway.
452 of 535. No location found for Finglas North, County Dublin United States.
453 of 535. No location found for Bahia Blanca, Buenos aires United States.
454 of 535. No location found for Darfo Baorio Terme Italy.
455 of 535. No location found for Barrington, Vic United States.
456 of 535. No location found for Saikung Hong Kong.
457 of 535. No location found for Palmyra, Western Australia United States.
458 of 535. No location found for East Freetown Italy.
459 of 535. No location found for Apo, Troms United States.
460 of 535. No location found for New Territories, Sham Tseng United States.
461 of 535. No location found for Mimato-Ku Japan.
462 of 535. No location found for Bandolbandol France.
463 of 535. No location found for Bezirk Marzahn-Hellersdorf Germany.
464 of 535. No location found for Oakleigh, Victoria United States.
465 of 535. No location found for Caba Bs As Argentina Argentina.
466 of 535. No location found for Hvittingfoss, Norway United States.
467 of 535. No location found for Queens, New York [NY] United States.
468 of 535. No location found for Whitlwy Bay United Kingdom.
469 of 535. No location found for Gam, Ciudad de Mexico United States.
470 of 535. No location found for St.Peteresburg Russian Federation.
471 of 535. No location found for Punaauia - Tahiti French Polynesia.
472 of 535. No location found for Cabo Rojo Northern Mariana Islands.
473 of 535. No location found for Weymouth, Gauteng United States.
474 of 535. No location found for Bezirk Friedrichshain-Kreuzberg Germany.
475 of 535. No location found for Brooklyln, NY United States.
476 of 535. No location found for Gratta Terme (Fc) Italy.
477 of 535. No location found for Vessy, Geneve United States.
478 of 535. No location found for Bangkok, Bangkok United States.
479 of 535. No location found for San Fracisco De Campeche Mexico.
480 of 535. No location found for Nr Bishop's Stortford United Kingdom.
481 of 535. No location found for Severna Parkseverna Park, MD United States.
482 of 535. No location found for Rignano Sul Arno Italy.
483 of 535. No location found for Kasugashi Japan.
484 of 535. No location found for San Antonio, TexasTx United States.
485 of 535. No location found for Beratzhausen Aruba.
486 of 535. No location found for Tampa, Nordrhein-Westfalen United States.
487 of 535. No location found for Northampton, Auckland City United States.
488 of 535. No location found for Guayllabamna Ecuador.
489 of 535. No location found for Yuenlong Hong Kong.
490 of 535. No location found for Washington, New JerseyWashington United States.
491 of 535. No location found for Kopavogi, Iceland United States.
492 of 535. No location found for Salzano Venice Italy.
493 of 535. No location found for Stavanger, Hafrsfjord United States.
494 of 535. No location found for Eagleville Italy.
495 of 535. No location found for Palmerston North, MANAWATU United States.
496 of 535. No location found for Bellingham, Norway United States.
497 of 535. No location found for Cfar Bialik Israel.
498 of 535. No location found for Beek - Ubergen Netherlands.
499 of 535. No location found for Monclair, NJ United States.
500 of 535. No location found for Mooloolaba, Queensland United States.
501 of 535. No location found for Banqiao Dist People's Republic of China.
502 of 535. No location found for Ikoyi, Lagos United States.
503 of 535. No location found for San Clemente, Californiac United States.
504 of 535. No location found for Durham, England United States.
505 of 535. No location found for Nøtterøy, Norway United States.
506 of 535. No location found for Guayaqsuil Ecuador.
507 of 535. No location found for Saint Louis, MissouriMO United States.

508 of 535. No location found for Esbo, Finland United States.
509 of 535. No location found for Kualalumpur Malaysia.
510 of 535. No location found for Apo, Oost Vlaanderen United States.
511 of 535. No location found for Worcester, Buenos aires United States.
512 of 535. No location found for Framingham, Metro Manila United States.
513 of 535. No location found for Bodegraven, Holandia Południowa United States.
514 of 535. No location found for Fort Worth, UNITED STATES United States.
515 of 535. No location found for Amphoe Dan Khun Thot Thailand.
516 of 535. No location found for Hungtington, NY United States.
517 of 535. No location found for Taguig City, Metro Manila United States.
518 of 535. Found location for Thonburi Thailand.
519 of 535. Found location for Wishart Australia.
520 of 535. Found location for Oadby United Kingdom.
521 of 535. Found location for Pollestres France.
522 of 535. No location found for Clearwater Bay, Sai Kung People's Republic of China.
523 of 535. No location found for Cossato, Biella United States.
524 of 535. No location found for Manchester, Connecticutt United States.
525 of 535. No location found for Cumberlnd Ctr, ME United States.
526 of 535. No location found for Alpharetta Indonesia.
527 of 535. No location found for Las Pinas, Metro Manila United States.
528 of 535. No location found for Mc Keesport, PA United States.
529 of 535. No location found for Raadal Norway.
530 of 535. No location found for Acton, NCR United States.
531 of 535. No location found for Huiquang Thailand.
532 of 535. No location found for Rabun Gap, GA United States.
533 of 535. No location found for Fukuokasi Japan.
534 of 535. No location found for Basidlon United Kingdom.
535 of 535. No location found for Argyull United Kingdom.

In [20]:
len(problem_locations)

530

In [21]:
problem_locations_df = pd.DataFrame(problem_locations)
problem_locations_df.to_csv('..00_data/geodata/problem_addresses.csv')

In [29]:
df['location'] = df['address'].apply(lambda address: location_dict[address] if address in location_dict else None)
df['latitude'] = df['location'].apply(lambda loc: loc.latitude if loc else None)
df['longitude'] = df['location'].apply(lambda loc: loc.longitude if loc else None)

In [24]:
df.location.isnull().sum()

53618

In [34]:
df['full_address'][0].loc

AttributeError: 'str' object has no attribute 'loc'

In [ ]:
address_cache_df = pd.DataFrame.from_dict(location_dict)
address_cache_df = address_cache_df.transpose()

In [ ]:
address_cache_df

In [ ]:
address_cache_df = address_cache_df.reset_index()
address_cache_df.rename(columns={'index': 'address', 0: 'full_address', 1: 'location'}, inplace=True)

In [ ]:
address_cache_df

In [ ]:
# define the path and name for the output file
output_csv = "..00_data/geodata/address_cache.csv"

import csv

# We want to match the order of columns if we are appending new entries to an existing file.
### Because we are using a dictionary to capture the race results, and of the way dictionaries are ordered,
### It is possible for different scraping runs to attempt to order the columns differently.
### That would be confusing, so we force whatever order was established in the first run.
### (The bottom line is that it would really be a good idea to use a database here instead.)

# Try to read the header from the existing file. If they exist, match the column order.
try:
    with open(output_csv, 'r', encoding="utf-8") as f:
        reader = csv.reader(f)
        header_list = next(reader)
        # It is possible to be missing columns, so check to see if we have everything.
        for x in header_list:
            if x not in address_cache_df.columns:
                address_cache_df[x] = ''
        address_cache_df = address_cache_df[header_list]
# If we weren't able to open the file, we are going to create one from scratch.
except:
    print(f"{output_csv} does not exist, so I'll create it!")

# This either creates the file, or appends to it without headers. We already took steps to make sure
# the columns in finishers_df match the headers (if they exist).
with open(output_csv, 'a', encoding="utf-8") as f:
    address_cache_df.to_csv(f, header=f.tell()==0, index = False, line_terminator = '\n')

In [ ]:
mapping_df = df[pd.notnull(df["latitude"])]

In [ ]:
mapping_df.info(verbose = True)

In [ ]:
df.info(verbose=True)

In [ ]:
map1 = folium.Map(
    location=[40.7128, -74.0060],
    tiles='cartodbpositron',
    zoom_start=12,
)

In [ ]:
mapping_df.apply(lambda row:folium.CircleMarker(location=[row["latitude"], row["longitude"]]).add_to(map1), axis=1)
map1

In [ ]:
map1.save("map7.html")

In [ ]:
folium_map = folium.Map(location=[40.7128, -74.0060],
                        zoom_start=12,
                        tiles='cartodbpositron')


FastMarkerCluster(data=list(zip(mapping_df['latitude'].values, mapping_df['longitude'].values))).add_to(folium_map)
folium.LayerControl().add_to(folium_map)
folium_map

In [ ]:
folium_map.save("map8.html")